services:
  postgres:
    image: postgres:18
    env_file: '.env'
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql

  neo4j:
    image: neo4j:5-community
    environment:
      - NEO4J_server_config_strict__validation_enabled=false
    env_file: '.env'
    ports:
      - '7474:7474' # Веб-интерфейс (Neo4j Browser)
      - '7687:7687' # Bolt-протокол для подключения из кода (драйверов)
    volumes:
      - ./volumes/neo4j/data:/data